language: java
jdk:
- openjdk8
- openjdk9
services: docker
env:
  matrix:
  - COVERAGE=0.9 TEST_TARGET=./monolithic/ui
  - COVERAGE=0.9 TEST_TARGET=./monolithic/service/cart
  - COVERAGE=0.9 TEST_TARGET=./monolithic/service/user
  - COVERAGE=0.35 TEST_TARGET=./monolithic/repository/order
  - COVERAGE=0.9 TEST_TARGET=./monolithic/repository/cart
  - COVERAGE=0.9 TEST_TARGET=./monolithic/repository/product
  - COVERAGE=0.31 TEST_TARGET=./monolithic/repository/user
  global:
  - secure: PTNnNOK1uoKppgdg7Zi0ng7OHnpqQlMHJmzyCXNDNk+hbMl1SzduNOemRU+A1je/phSzvNNO1AFjUL0n5oB07w+2S8Uvc170DHS7Ui+SwBqly0uWvioHPUdm8SKc4LxfBxXhXSB2+f1q15p6B2lW7u+sHV63HonW1dBjmoG/+fl3rK+vjTx+RfbqInn+JeFvFuNX/MrF0z1qg+DWLCGhV1bzYVf7Gio1EievCXcxg/Od89FbBSyJi2leMM+qfxnQbYGFSdh7QA/KR1m6+MIKLM9GJdKHX992fco2qYOeU5QzM2u5oWl0RzqGzsqfR9nHfcbghZKBCqHugf/E3Q44hhfK8wFMMWfTXCC9Zh9okicvHnHThr+JBYB0MFMX5n9DcmeSonXFVQwnEVZXPbjwC/mrMq9CUW3AVutKSypH/ugC25KSY3q0hGGvFDGAPacYqAX9EOFHNgc69H/g7OK9Z4hxSkQxUsQRngwnBk8k5Bm96zmWCU2VTB35oUVCWqjIzcl3a7LK0uLLGgk/w3NRqE+2glXhwswcedvAYJcdyOmdvmdqhYfOblysn7L6+HsTrnMA8fbxlDjWr3/r2WJzYyKtSieisR8kgZ4OeqUJ7BM45zyrnz7VURVXqmEXFxpvcCKp8T43mqP4LW9vRQ4IKjB2zx9mVcLiE4FZr9qGBnw=
install:
- "./gradlew clean jar"
script:
- "./gradlew -p $TEST_TARGET check"
after_success:
- find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
deploy:
  provider: script
  script: bash -c "echo \"${DOCKER_PASSWORD}\" | docker login --username \"${DOCKER_LOGIN}\"
    --password-stdin ;"
  on:
    all_branches: true
